name: Trigger auto deployment for tronicsify-rag

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/tronicsify-rag-AutoDeployTrigger-8b43076b-669f-46a1-a994-a28eec8d5e57.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TRONICSIFYRAG_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TRONICSIFYRAG_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TRONICSIFYRAG_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.TRONICSIFYRAG_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TRONICSIFYRAG_REGISTRY_PASSWORD }}
          containerAppName: tronicsify-rag
          resourceGroup: tronicsify
          imageToBuild: trungngvu/tronicsify-rag:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


